<?php
header("Access-Control-Allow-Origin: *"); // Allow all origins
header("Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS"); // Allow HTTP methods
header("Access-Control-Allow-Headers: Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With"); // Allow specific headers
header("Content-Type: application/json; charset=UTF-8"); // Specify JSON response format

$outputArr = [
	array(
		'id' => '0',
		'stockCategory' => 'worlds-largest-companies',
		'longTitle' => 'Large cap global companies',
		'shortTitle' => 'Large Cap',
		'desc' => 'Filtered by market cap, the API shows companies with the biggest market value in the world. Analyze carefully and consider all stats to find new opportunities.'
	),
	array(
		'id' => '1',
		'stockCategory' => 'worlds-non-us-companies',
		'longTitle' => 'Largest non-U.S. companies by market cap',
		'shortTitle' => 'Largest non-U.S.',
		'desc' => 'The API lets you watch international companies with the largest market capitalization. Track Chinese, Indian, and other stocks to diversify your portfolio and benefit from market globalization.'
	),
	array(
		'id' => '2',
		'stockCategory' => 'worlds-largest-employers',
		'longTitle' => 'World biggest employers',
		'shortTitle' => 'Largest employers',
		'desc' => 'A high number of employees indicates that a company is growing or already considered established. See the list of companies with the largest workforce in the world, they might make a reliable addition to your portfolio.'
	),
	array(
		'id' => '3',
		'stockCategory' => 'worlds-highest-revenue',
		'longTitle' => 'Global companies with the highest revenue',
		'shortTitle' => 'Highest revenue',
		'desc' => 'Global growth investors will benefit from our list: it contains companies with the highest revenue, which indicates a greater potential worldwide. Consider additional metrics such as market cap for a comprehensive analysis.'
	),
	array(
		'id' => '4',
		'stockCategory' => 'worlds-highest-revenue-per-employee',
		'longTitle' => 'Companies with the most revenue per employee',
		'shortTitle' => 'Highest revenue per employee',
		'desc' => 'We gathered global companies with the highest revenue per employee in the API. With leaders on top, the list also features stock price, market cap, and other stats.'
	),
	array(
		'id' => '5',
		'stockCategory' => 'worlds-highest-profit-per-employee',
		'longTitle' => 'Companies with the highest profit per employee',
		'shortTitle' => 'Highest profit per employee',
		'desc' => 'we gathered global companies with the most profit generated by each staff member: sorted in descending order and supplied with other stats, it can help create a more balanced portfolio.'
	),
	array(
		'id' => '6',
		'stockCategory' => 'worlds-highest-earnings',
		'longTitle' => 'Most profitable companies in the world',
		'shortTitle' => 'Highest earnings',
		'desc' => 'This API helps you find top world\'s companies with the highest earnings. See them sorted by net income and make your portfolio more balanced with stocks from around the world.'
	),
	array(
		'id' => '7',
		'stockCategory' => 'worlds-highest-dividends',
		'longTitle' => 'World\'s companies with the highest dividend yields',
		'shortTitle' => 'High-dividend',
		'desc' => 'Check out the top dividend-paying companies around the world. Use their change, volume, and other metrics and financials to make the right choice.'
	),
	array(
		'id' => '8',
		'stockCategory' => 'worlds-largest-oil-and-gas-companies',
		'longTitle' => 'World leaders in the oil and gas industry',
		'shortTitle' => 'Oil And Gas',
		'desc' => 'we gathered the biggest names in the industry. Choose the best stocks, but remember that many factors can easily influence oil and gas prices, so you should always do your own research before making a decision.'
	),
	array(
		'id' => '9',
		'stockCategory' => 'worlds-largest-semiconductors-producers',
		'longTitle' => 'Leading semiconductor producers',
		'shortTitle' => 'Semiconductors',
		'desc' => 'We prepared a list of the largest companies engaged in manufacturing of semiconductors. Sorted by market cap, they present new opportunities for your portfolio. Still, use available stats to prepare a detailed analysis.'
	),
	array(
		'id' => '10',
		'stockCategory' => 'worlds-largest-telecommunication-companies',
		'longTitle' => 'Leaders of the telecommunications sector',
		'shortTitle' => 'Telecom',
		'desc' => 'Telecommunications are a fast-growing and competitive sector. Below, you can see its giants and their various stats like market cap and volume. DYOR before making a decision.'
	),
	array(
		'id' => '11',
		'stockCategory' => 'worlds-largest-tech-companies',
		'longTitle' => 'World tech leaders',
		'shortTitle' => 'Tech',
		'desc' => 'Here you\'ll find the leaders of the industry engaged in providing information technology services, production and distribution of electronic components, and many other things. Choose wisely and prepare before making a decision.'
	),
	array(
		'id' => '12',
		'stockCategory' => 'worlds-largest-biotech-companies',
		'longTitle' => 'Largest biotechnology companies',
		'shortTitle' => 'Biotech',
		'desc' => 'We gathered stocks of the world\'s biggest biotech companies. They\'re at the forefront of science, but attract investors for more practical reasons. See them sorted by market cap and equipped with various stats below.'
	),
	array(
		'id' => '13',
		'stockCategory' => 'worlds-largest-finance-companies',
		'longTitle' => 'World\'s largest finance companies',
		'shortTitle' => 'Finance',
		'desc' => 'We made a list of global leaders in finance, dealing in rental, leasing, and more. They\'re sorted by market cap and equipped with other stats too, including price and change, so choose wisely.'
	),
	array(
		'id' => '14',
		'stockCategory' => 'worlds-largest-banks',
		'longTitle' => 'Leaders of the world banking sector',
		'shortTitle' => 'Banks',
		'desc' => 'We gathered the largest banks worldwide in one place: below, you\'ll find major investment banks and brokers, regional and saving banks. Sorted by market cap, the list also contains other helpful stats: stock price, change, etc.'
	),
	array(
		'id' => '15',
		'stockCategory' => 'worlds-largest-e-commerce-companies',
		'longTitle' => 'Leaders in the world of e-commerce',
		'shortTitle' => 'E-Commerce',
		'desc' => 'The e-commerce sector is big and growing – it includes internet retail, electronics and appliance stores, for example. Look at the list below and choose the most attractive stocks by market cap, price, volume and other stats.'
	),
	array(
		'id' => '16',
		'stockCategory' => 'worlds-largest-software-companies',
		'longTitle' => 'Top of the software world',
		'shortTitle' => 'Software',
		'desc' => 'Find the list of the world leading software providers below. Sorted by market cap, the list also features stock price, change, volume, and other helpful stats to design a reliable strategy.'
	),
	array(
		'id' => '17',
		'stockCategory' => 'worlds-largest-automakers',
		'longTitle' => 'World top automakers',
		'shortTitle' => 'Automakers',
		'desc' => 'Here we gathered the world\'s top companies engaged in the production of all kinds of motor vehicles. Choose the best option for your portfolio by analyzing their market cap, price change, and other helpful stats.'
	),
	array(
		'id' => '18',
		'stockCategory' => 'worlds-largest-hotels-and-resorts',
		'longTitle' => 'Leaders in the recreation industry',
		'shortTitle' => 'Hotels and Resorts',
		'desc' => 'In the API you\'ll find the largest hotels, resorts and cruise lines the industry can offer. Make sure to take a good look at their stock price, volume, and other metrics before adding to your portfolio.'
	),
	array(
		'id' => '19',
		'stockCategory' => 'worlds-largest-restaurant-chains',
		'longTitle' => 'Leaders in the restaurant business',
		'shortTitle' => 'Restaurants',
		'desc' => 'We\'ve prepared a list of the world leading restaurants. See them sorted by market cap and equipped with performance stats, income statement and more to make an informed decision.'
	),
	array(
		'id' => '20',
		'stockCategory' => 'worlds-largest-stores',
		'longTitle' => 'World shopping giants',
		'shortTitle' => 'Stores',
		'desc' => 'We\'ve gathered world largest department stores, discount stores, electronic and appliances stores, and more. They\'re sorted by market cap, supplied with dividends, income statement, and other info for a better decision-making.'
	),
	array(
		'id' => '21',
		'stockCategory' => 'worlds-largest-beverage-companies',
		'longTitle' => 'World leading drinks producers',
		'shortTitle' => 'Beverages',
		'desc' => 'Here we\'ve gathered world largest producers of beverages, both alcoholic and non-alcoholic. Choose wisely and consider all available stats: market cap, stock price, and other.'
	),
	array(
		'id' => '22',
		'stockCategory' => 'worlds-largest-food-companies',
		'longTitle' => 'World leaders in the food industry',
		'shortTitle' => 'Food',
		'desc' => 'The API comprises the biggest food companies in the world: food retailers, distributors, companies that provide fish, meat, dairy, candy, and other edibles. Check their stats to make a better decision.'
	)
];
$outputJsonArr = array('status' => 'success', 'data' => $outputArr);
echo json_encode($outputJsonArr, JSON_UNESCAPED_SLASHES);
exit();
